#Common
label: gitops

#Deployment
replicas: 3
image:
  repository: asia.gcr.io/bubbly-area-374506/china_gcp_learning # 変更箇所 DOCKERHUB_REPO_NAME
  tag: 77a99a6022669a3ee09836f87f078236d8861160

imageConfig:
  pullPolicy: IfNotPresent

#Service
service_type: LoadBalancer
